FROM eclipse-temurin:17-jre
WORKDIR /app

# Copy the pre-built JAR file
COPY target/*.jar app.jar

# Set production profile
ENV SPRING_PROFILES_ACTIVE=docker

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
